
export const events = {
  TRIPS_STATES_CREATED: 'TRIPS_STATES_CREATED',
  TRIPS_STATES_ENDED: 'TRIPS_STATES_ENDED',

  REAL_TIME_TRIP_CREATED: 'REAL_TIME_TRIP_CREATED',
  REAL_TIME_TRIP_PLANNED: 'REAL_TIME_TRIP_PLANNED',
  REAL_TIME_TRIP_NOT_PLANNED: 'REAL_TIME_TRIP_NOT_PLANNED',
  REAL_TIME_TRIP_ARRIVED: 'REAL_TIME_TRIP_ARRIVED',
  REAL_TIME_TRIP_CANCELED: 'REAL_TIME_TRIP_CANCELED',
  REAL_TIME_TRIP_DELAYED: 'REAL_TIME_TRIP_DELAYED',
  REAL_TIME_TRIP_RUNNING: 'REAL_TIME_TRIP_RUNNING'
};
