
export const RealTimeStatus = {
  OFFLINE: "OFFLINE",
  ONLINE: "ONLINE",
  CHECKING: "CHECKING"
};

export const tripStates = {
  TRIP_PLANNED: 'TRIP_PLANNED',
  NOT_PLANNED_TRIP: 'NOT_PLANNED_TRIP',
  ARRIVED_TRIP: 'ARRIVED_TRIP',
  CANCELLED_TRIP: 'CANCELLED_TRIP',
  DELAYED_TRIP: 'DELAYED_TRIP',
  RUNNING_TRIP: 'RUNNING_TRIP'
};
