
export const events = {
  STOP_VIEWER_CREATED: 'STOP_VIEWER_CREATED',
  STOP_VIEWER_UPDATED: 'STOP_VIEWER_UPDATED',
  STOP_VIEWER_TRIPS_GENERATED: 'STOP_VIEWER_TRIPS_GENERATED',
  STOP_VIEWER_TRIPS_ENDED: 'STOP_VIEWER_TRIPS_ENDED'
};
